// <auto-generated /> - produced by protgen/protogen.py; do not edit by hand.
#pragma once

#include <stdexcept>
#include <string>

#include "protocol/protocol.h"

// A single string-dispatched DAP service base.

namespace dap_dbgeng::protocol
{

class unhandled_dap_request : public std::runtime_error
{
  public:
    unhandled_dap_request(int request_seq, std::string command)
        : std::runtime_error("No handler implemented for DAP request " + command),
          request_seq(request_seq), command(std::move(command))
    {
    }
    int request_seq;
    std::string command;
};

class dap_service
{
  public:
    virtual ~dap_service() = default;

    void handle(const nlohmann::json& message)
    {
        const std::string type = message.value("type", std::string{});
        if (type == "request")
            return dispatch_request(message);
        if (type == "event")
            return dispatch_event(message);
        if (type == "response")
            return dispatch_response(message);
        throw std::runtime_error("Unsupported DAP message type: " + type);
    }

  protected:
    virtual void handle_attach_request(const AttachRequest& request)
    {
        throw unhandled_dap_request(request.seq, "attach");
    }
    virtual void handle_breakpoint_locations_request(const BreakpointLocationsRequest& request)
    {
        throw unhandled_dap_request(request.seq, "breakpointLocations");
    }
    virtual void handle_cancel_request(const CancelRequest& request)
    {
        throw unhandled_dap_request(request.seq, "cancel");
    }
    virtual void handle_completions_request(const CompletionsRequest& request)
    {
        throw unhandled_dap_request(request.seq, "completions");
    }
    virtual void handle_configuration_done_request(const ConfigurationDoneRequest& request)
    {
        throw unhandled_dap_request(request.seq, "configurationDone");
    }
    virtual void handle_continue_request(const ContinueRequest& request)
    {
        throw unhandled_dap_request(request.seq, "continue");
    }
    virtual void handle_data_breakpoint_info_request(const DataBreakpointInfoRequest& request)
    {
        throw unhandled_dap_request(request.seq, "dataBreakpointInfo");
    }
    virtual void handle_disassemble_request(const DisassembleRequest& request)
    {
        throw unhandled_dap_request(request.seq, "disassemble");
    }
    virtual void handle_disconnect_request(const DisconnectRequest& request)
    {
        throw unhandled_dap_request(request.seq, "disconnect");
    }
    virtual void handle_evaluate_request(const EvaluateRequest& request)
    {
        throw unhandled_dap_request(request.seq, "evaluate");
    }
    virtual void handle_exception_info_request(const ExceptionInfoRequest& request)
    {
        throw unhandled_dap_request(request.seq, "exceptionInfo");
    }
    virtual void handle_goto_request(const GotoRequest& request)
    {
        throw unhandled_dap_request(request.seq, "goto");
    }
    virtual void handle_goto_targets_request(const GotoTargetsRequest& request)
    {
        throw unhandled_dap_request(request.seq, "gotoTargets");
    }
    virtual void handle_initialize_request(const InitializeRequest& request)
    {
        throw unhandled_dap_request(request.seq, "initialize");
    }
    virtual void handle_launch_request(const LaunchRequest& request)
    {
        throw unhandled_dap_request(request.seq, "launch");
    }
    virtual void handle_loaded_sources_request(const LoadedSourcesRequest& request)
    {
        throw unhandled_dap_request(request.seq, "loadedSources");
    }
    virtual void handle_locations_request(const LocationsRequest& request)
    {
        throw unhandled_dap_request(request.seq, "locations");
    }
    virtual void handle_modules_request(const ModulesRequest& request)
    {
        throw unhandled_dap_request(request.seq, "modules");
    }
    virtual void handle_next_request(const NextRequest& request)
    {
        throw unhandled_dap_request(request.seq, "next");
    }
    virtual void handle_pause_request(const PauseRequest& request)
    {
        throw unhandled_dap_request(request.seq, "pause");
    }
    virtual void handle_read_memory_request(const ReadMemoryRequest& request)
    {
        throw unhandled_dap_request(request.seq, "readMemory");
    }
    virtual void handle_restart_request(const RestartRequest& request)
    {
        throw unhandled_dap_request(request.seq, "restart");
    }
    virtual void handle_restart_frame_request(const RestartFrameRequest& request)
    {
        throw unhandled_dap_request(request.seq, "restartFrame");
    }
    virtual void handle_reverse_continue_request(const ReverseContinueRequest& request)
    {
        throw unhandled_dap_request(request.seq, "reverseContinue");
    }
    virtual void handle_run_in_terminal_request(const RunInTerminalRequest& request)
    {
        throw unhandled_dap_request(request.seq, "runInTerminal");
    }
    virtual void handle_scopes_request(const ScopesRequest& request)
    {
        throw unhandled_dap_request(request.seq, "scopes");
    }
    virtual void handle_set_breakpoints_request(const SetBreakpointsRequest& request)
    {
        throw unhandled_dap_request(request.seq, "setBreakpoints");
    }
    virtual void handle_set_data_breakpoints_request(const SetDataBreakpointsRequest& request)
    {
        throw unhandled_dap_request(request.seq, "setDataBreakpoints");
    }
    virtual void handle_set_exception_breakpoints_request(const SetExceptionBreakpointsRequest& request)
    {
        throw unhandled_dap_request(request.seq, "setExceptionBreakpoints");
    }
    virtual void handle_set_expression_request(const SetExpressionRequest& request)
    {
        throw unhandled_dap_request(request.seq, "setExpression");
    }
    virtual void handle_set_function_breakpoints_request(const SetFunctionBreakpointsRequest& request)
    {
        throw unhandled_dap_request(request.seq, "setFunctionBreakpoints");
    }
    virtual void handle_set_instruction_breakpoints_request(const SetInstructionBreakpointsRequest& request)
    {
        throw unhandled_dap_request(request.seq, "setInstructionBreakpoints");
    }
    virtual void handle_set_variable_request(const SetVariableRequest& request)
    {
        throw unhandled_dap_request(request.seq, "setVariable");
    }
    virtual void handle_source_request(const SourceRequest& request)
    {
        throw unhandled_dap_request(request.seq, "source");
    }
    virtual void handle_stack_trace_request(const StackTraceRequest& request)
    {
        throw unhandled_dap_request(request.seq, "stackTrace");
    }
    virtual void handle_start_debugging_request(const StartDebuggingRequest& request)
    {
        throw unhandled_dap_request(request.seq, "startDebugging");
    }
    virtual void handle_step_back_request(const StepBackRequest& request)
    {
        throw unhandled_dap_request(request.seq, "stepBack");
    }
    virtual void handle_step_in_request(const StepInRequest& request)
    {
        throw unhandled_dap_request(request.seq, "stepIn");
    }
    virtual void handle_step_in_targets_request(const StepInTargetsRequest& request)
    {
        throw unhandled_dap_request(request.seq, "stepInTargets");
    }
    virtual void handle_step_out_request(const StepOutRequest& request)
    {
        throw unhandled_dap_request(request.seq, "stepOut");
    }
    virtual void handle_terminate_request(const TerminateRequest& request)
    {
        throw unhandled_dap_request(request.seq, "terminate");
    }
    virtual void handle_terminate_threads_request(const TerminateThreadsRequest& request)
    {
        throw unhandled_dap_request(request.seq, "terminateThreads");
    }
    virtual void handle_threads_request(const ThreadsRequest& request)
    {
        throw unhandled_dap_request(request.seq, "threads");
    }
    virtual void handle_variables_request(const VariablesRequest& request)
    {
        throw unhandled_dap_request(request.seq, "variables");
    }
    virtual void handle_write_memory_request(const WriteMemoryRequest& request)
    {
        throw unhandled_dap_request(request.seq, "writeMemory");
    }

    virtual void handle_breakpoint_event(const BreakpointEvent& event)
    {
        (void)event;
    }
    virtual void handle_capabilities_event(const CapabilitiesEvent& event)
    {
        (void)event;
    }
    virtual void handle_continued_event(const ContinuedEvent& event)
    {
        (void)event;
    }
    virtual void handle_exited_event(const ExitedEvent& event)
    {
        (void)event;
    }
    virtual void handle_initialized_event(const InitializedEvent& event)
    {
        (void)event;
    }
    virtual void handle_invalidated_event(const InvalidatedEvent& event)
    {
        (void)event;
    }
    virtual void handle_loaded_source_event(const LoadedSourceEvent& event)
    {
        (void)event;
    }
    virtual void handle_memory_event(const MemoryEvent& event)
    {
        (void)event;
    }
    virtual void handle_module_event(const ModuleEvent& event)
    {
        (void)event;
    }
    virtual void handle_output_event(const OutputEvent& event)
    {
        (void)event;
    }
    virtual void handle_process_event(const ProcessEvent& event)
    {
        (void)event;
    }
    virtual void handle_progress_end_event(const ProgressEndEvent& event)
    {
        (void)event;
    }
    virtual void handle_progress_start_event(const ProgressStartEvent& event)
    {
        (void)event;
    }
    virtual void handle_progress_update_event(const ProgressUpdateEvent& event)
    {
        (void)event;
    }
    virtual void handle_stopped_event(const StoppedEvent& event)
    {
        (void)event;
    }
    virtual void handle_terminated_event(const TerminatedEvent& event)
    {
        (void)event;
    }
    virtual void handle_thread_event(const ThreadEvent& event)
    {
        (void)event;
    }

    virtual void handle_attach_response(const AttachResponse& response)
    {
        (void)response;
    }
    virtual void handle_breakpoint_locations_response(const BreakpointLocationsResponse& response)
    {
        (void)response;
    }
    virtual void handle_cancel_response(const CancelResponse& response)
    {
        (void)response;
    }
    virtual void handle_completions_response(const CompletionsResponse& response)
    {
        (void)response;
    }
    virtual void handle_configuration_done_response(const ConfigurationDoneResponse& response)
    {
        (void)response;
    }
    virtual void handle_continue_response(const ContinueResponse& response)
    {
        (void)response;
    }
    virtual void handle_data_breakpoint_info_response(const DataBreakpointInfoResponse& response)
    {
        (void)response;
    }
    virtual void handle_disassemble_response(const DisassembleResponse& response)
    {
        (void)response;
    }
    virtual void handle_disconnect_response(const DisconnectResponse& response)
    {
        (void)response;
    }
    virtual void handle_evaluate_response(const EvaluateResponse& response)
    {
        (void)response;
    }
    virtual void handle_exception_info_response(const ExceptionInfoResponse& response)
    {
        (void)response;
    }
    virtual void handle_goto_response(const GotoResponse& response)
    {
        (void)response;
    }
    virtual void handle_goto_targets_response(const GotoTargetsResponse& response)
    {
        (void)response;
    }
    virtual void handle_initialize_response(const InitializeResponse& response)
    {
        (void)response;
    }
    virtual void handle_launch_response(const LaunchResponse& response)
    {
        (void)response;
    }
    virtual void handle_loaded_sources_response(const LoadedSourcesResponse& response)
    {
        (void)response;
    }
    virtual void handle_locations_response(const LocationsResponse& response)
    {
        (void)response;
    }
    virtual void handle_modules_response(const ModulesResponse& response)
    {
        (void)response;
    }
    virtual void handle_next_response(const NextResponse& response)
    {
        (void)response;
    }
    virtual void handle_pause_response(const PauseResponse& response)
    {
        (void)response;
    }
    virtual void handle_read_memory_response(const ReadMemoryResponse& response)
    {
        (void)response;
    }
    virtual void handle_restart_response(const RestartResponse& response)
    {
        (void)response;
    }
    virtual void handle_restart_frame_response(const RestartFrameResponse& response)
    {
        (void)response;
    }
    virtual void handle_reverse_continue_response(const ReverseContinueResponse& response)
    {
        (void)response;
    }
    virtual void handle_run_in_terminal_response(const RunInTerminalResponse& response)
    {
        (void)response;
    }
    virtual void handle_scopes_response(const ScopesResponse& response)
    {
        (void)response;
    }
    virtual void handle_set_breakpoints_response(const SetBreakpointsResponse& response)
    {
        (void)response;
    }
    virtual void handle_set_data_breakpoints_response(const SetDataBreakpointsResponse& response)
    {
        (void)response;
    }
    virtual void handle_set_exception_breakpoints_response(const SetExceptionBreakpointsResponse& response)
    {
        (void)response;
    }
    virtual void handle_set_expression_response(const SetExpressionResponse& response)
    {
        (void)response;
    }
    virtual void handle_set_function_breakpoints_response(const SetFunctionBreakpointsResponse& response)
    {
        (void)response;
    }
    virtual void handle_set_instruction_breakpoints_response(const SetInstructionBreakpointsResponse& response)
    {
        (void)response;
    }
    virtual void handle_set_variable_response(const SetVariableResponse& response)
    {
        (void)response;
    }
    virtual void handle_source_response(const SourceResponse& response)
    {
        (void)response;
    }
    virtual void handle_stack_trace_response(const StackTraceResponse& response)
    {
        (void)response;
    }
    virtual void handle_start_debugging_response(const StartDebuggingResponse& response)
    {
        (void)response;
    }
    virtual void handle_step_back_response(const StepBackResponse& response)
    {
        (void)response;
    }
    virtual void handle_step_in_response(const StepInResponse& response)
    {
        (void)response;
    }
    virtual void handle_step_in_targets_response(const StepInTargetsResponse& response)
    {
        (void)response;
    }
    virtual void handle_step_out_response(const StepOutResponse& response)
    {
        (void)response;
    }
    virtual void handle_terminate_response(const TerminateResponse& response)
    {
        (void)response;
    }
    virtual void handle_terminate_threads_response(const TerminateThreadsResponse& response)
    {
        (void)response;
    }
    virtual void handle_threads_response(const ThreadsResponse& response)
    {
        (void)response;
    }
    virtual void handle_variables_response(const VariablesResponse& response)
    {
        (void)response;
    }
    virtual void handle_write_memory_response(const WriteMemoryResponse& response)
    {
        (void)response;
    }

    virtual void handle_request(const Request& request)
    {
        throw unhandled_dap_request(request.seq, request.command);
    }

  private:
    void dispatch_request(const nlohmann::json& m)
    {
        const std::string command = m.value("command", std::string{});
        if (command == "attach")
            return handle_attach_request(m.get<AttachRequest>());
        if (command == "breakpointLocations")
            return handle_breakpoint_locations_request(m.get<BreakpointLocationsRequest>());
        if (command == "cancel")
            return handle_cancel_request(m.get<CancelRequest>());
        if (command == "completions")
            return handle_completions_request(m.get<CompletionsRequest>());
        if (command == "configurationDone")
            return handle_configuration_done_request(m.get<ConfigurationDoneRequest>());
        if (command == "continue")
            return handle_continue_request(m.get<ContinueRequest>());
        if (command == "dataBreakpointInfo")
            return handle_data_breakpoint_info_request(m.get<DataBreakpointInfoRequest>());
        if (command == "disassemble")
            return handle_disassemble_request(m.get<DisassembleRequest>());
        if (command == "disconnect")
            return handle_disconnect_request(m.get<DisconnectRequest>());
        if (command == "evaluate")
            return handle_evaluate_request(m.get<EvaluateRequest>());
        if (command == "exceptionInfo")
            return handle_exception_info_request(m.get<ExceptionInfoRequest>());
        if (command == "goto")
            return handle_goto_request(m.get<GotoRequest>());
        if (command == "gotoTargets")
            return handle_goto_targets_request(m.get<GotoTargetsRequest>());
        if (command == "initialize")
            return handle_initialize_request(m.get<InitializeRequest>());
        if (command == "launch")
            return handle_launch_request(m.get<LaunchRequest>());
        if (command == "loadedSources")
            return handle_loaded_sources_request(m.get<LoadedSourcesRequest>());
        if (command == "locations")
            return handle_locations_request(m.get<LocationsRequest>());
        if (command == "modules")
            return handle_modules_request(m.get<ModulesRequest>());
        if (command == "next")
            return handle_next_request(m.get<NextRequest>());
        if (command == "pause")
            return handle_pause_request(m.get<PauseRequest>());
        if (command == "readMemory")
            return handle_read_memory_request(m.get<ReadMemoryRequest>());
        if (command == "restart")
            return handle_restart_request(m.get<RestartRequest>());
        if (command == "restartFrame")
            return handle_restart_frame_request(m.get<RestartFrameRequest>());
        if (command == "reverseContinue")
            return handle_reverse_continue_request(m.get<ReverseContinueRequest>());
        if (command == "runInTerminal")
            return handle_run_in_terminal_request(m.get<RunInTerminalRequest>());
        if (command == "scopes")
            return handle_scopes_request(m.get<ScopesRequest>());
        if (command == "setBreakpoints")
            return handle_set_breakpoints_request(m.get<SetBreakpointsRequest>());
        if (command == "setDataBreakpoints")
            return handle_set_data_breakpoints_request(m.get<SetDataBreakpointsRequest>());
        if (command == "setExceptionBreakpoints")
            return handle_set_exception_breakpoints_request(m.get<SetExceptionBreakpointsRequest>());
        if (command == "setExpression")
            return handle_set_expression_request(m.get<SetExpressionRequest>());
        if (command == "setFunctionBreakpoints")
            return handle_set_function_breakpoints_request(m.get<SetFunctionBreakpointsRequest>());
        if (command == "setInstructionBreakpoints")
            return handle_set_instruction_breakpoints_request(m.get<SetInstructionBreakpointsRequest>());
        if (command == "setVariable")
            return handle_set_variable_request(m.get<SetVariableRequest>());
        if (command == "source")
            return handle_source_request(m.get<SourceRequest>());
        if (command == "stackTrace")
            return handle_stack_trace_request(m.get<StackTraceRequest>());
        if (command == "startDebugging")
            return handle_start_debugging_request(m.get<StartDebuggingRequest>());
        if (command == "stepBack")
            return handle_step_back_request(m.get<StepBackRequest>());
        if (command == "stepIn")
            return handle_step_in_request(m.get<StepInRequest>());
        if (command == "stepInTargets")
            return handle_step_in_targets_request(m.get<StepInTargetsRequest>());
        if (command == "stepOut")
            return handle_step_out_request(m.get<StepOutRequest>());
        if (command == "terminate")
            return handle_terminate_request(m.get<TerminateRequest>());
        if (command == "terminateThreads")
            return handle_terminate_threads_request(m.get<TerminateThreadsRequest>());
        if (command == "threads")
            return handle_threads_request(m.get<ThreadsRequest>());
        if (command == "variables")
            return handle_variables_request(m.get<VariablesRequest>());
        if (command == "writeMemory")
            return handle_write_memory_request(m.get<WriteMemoryRequest>());
        return handle_request(m.get<Request>());
    }

    void dispatch_event(const nlohmann::json& m)
    {
        const std::string name = m.value("event", std::string{});
        if (name == "breakpoint")
            return handle_breakpoint_event(m.get<BreakpointEvent>());
        if (name == "capabilities")
            return handle_capabilities_event(m.get<CapabilitiesEvent>());
        if (name == "continued")
            return handle_continued_event(m.get<ContinuedEvent>());
        if (name == "exited")
            return handle_exited_event(m.get<ExitedEvent>());
        if (name == "initialized")
            return handle_initialized_event(m.get<InitializedEvent>());
        if (name == "invalidated")
            return handle_invalidated_event(m.get<InvalidatedEvent>());
        if (name == "loadedSource")
            return handle_loaded_source_event(m.get<LoadedSourceEvent>());
        if (name == "memory")
            return handle_memory_event(m.get<MemoryEvent>());
        if (name == "module")
            return handle_module_event(m.get<ModuleEvent>());
        if (name == "output")
            return handle_output_event(m.get<OutputEvent>());
        if (name == "process")
            return handle_process_event(m.get<ProcessEvent>());
        if (name == "progressEnd")
            return handle_progress_end_event(m.get<ProgressEndEvent>());
        if (name == "progressStart")
            return handle_progress_start_event(m.get<ProgressStartEvent>());
        if (name == "progressUpdate")
            return handle_progress_update_event(m.get<ProgressUpdateEvent>());
        if (name == "stopped")
            return handle_stopped_event(m.get<StoppedEvent>());
        if (name == "terminated")
            return handle_terminated_event(m.get<TerminatedEvent>());
        if (name == "thread")
            return handle_thread_event(m.get<ThreadEvent>());
    }

    void dispatch_response(const nlohmann::json& m)
    {
        const std::string command = m.value("command", std::string{});
        if (command == "attach")
            return handle_attach_response(m.get<AttachResponse>());
        if (command == "breakpointLocations")
            return handle_breakpoint_locations_response(m.get<BreakpointLocationsResponse>());
        if (command == "cancel")
            return handle_cancel_response(m.get<CancelResponse>());
        if (command == "completions")
            return handle_completions_response(m.get<CompletionsResponse>());
        if (command == "configurationDone")
            return handle_configuration_done_response(m.get<ConfigurationDoneResponse>());
        if (command == "continue")
            return handle_continue_response(m.get<ContinueResponse>());
        if (command == "dataBreakpointInfo")
            return handle_data_breakpoint_info_response(m.get<DataBreakpointInfoResponse>());
        if (command == "disassemble")
            return handle_disassemble_response(m.get<DisassembleResponse>());
        if (command == "disconnect")
            return handle_disconnect_response(m.get<DisconnectResponse>());
        if (command == "evaluate")
            return handle_evaluate_response(m.get<EvaluateResponse>());
        if (command == "exceptionInfo")
            return handle_exception_info_response(m.get<ExceptionInfoResponse>());
        if (command == "goto")
            return handle_goto_response(m.get<GotoResponse>());
        if (command == "gotoTargets")
            return handle_goto_targets_response(m.get<GotoTargetsResponse>());
        if (command == "initialize")
            return handle_initialize_response(m.get<InitializeResponse>());
        if (command == "launch")
            return handle_launch_response(m.get<LaunchResponse>());
        if (command == "loadedSources")
            return handle_loaded_sources_response(m.get<LoadedSourcesResponse>());
        if (command == "locations")
            return handle_locations_response(m.get<LocationsResponse>());
        if (command == "modules")
            return handle_modules_response(m.get<ModulesResponse>());
        if (command == "next")
            return handle_next_response(m.get<NextResponse>());
        if (command == "pause")
            return handle_pause_response(m.get<PauseResponse>());
        if (command == "readMemory")
            return handle_read_memory_response(m.get<ReadMemoryResponse>());
        if (command == "restart")
            return handle_restart_response(m.get<RestartResponse>());
        if (command == "restartFrame")
            return handle_restart_frame_response(m.get<RestartFrameResponse>());
        if (command == "reverseContinue")
            return handle_reverse_continue_response(m.get<ReverseContinueResponse>());
        if (command == "runInTerminal")
            return handle_run_in_terminal_response(m.get<RunInTerminalResponse>());
        if (command == "scopes")
            return handle_scopes_response(m.get<ScopesResponse>());
        if (command == "setBreakpoints")
            return handle_set_breakpoints_response(m.get<SetBreakpointsResponse>());
        if (command == "setDataBreakpoints")
            return handle_set_data_breakpoints_response(m.get<SetDataBreakpointsResponse>());
        if (command == "setExceptionBreakpoints")
            return handle_set_exception_breakpoints_response(m.get<SetExceptionBreakpointsResponse>());
        if (command == "setExpression")
            return handle_set_expression_response(m.get<SetExpressionResponse>());
        if (command == "setFunctionBreakpoints")
            return handle_set_function_breakpoints_response(m.get<SetFunctionBreakpointsResponse>());
        if (command == "setInstructionBreakpoints")
            return handle_set_instruction_breakpoints_response(m.get<SetInstructionBreakpointsResponse>());
        if (command == "setVariable")
            return handle_set_variable_response(m.get<SetVariableResponse>());
        if (command == "source")
            return handle_source_response(m.get<SourceResponse>());
        if (command == "stackTrace")
            return handle_stack_trace_response(m.get<StackTraceResponse>());
        if (command == "startDebugging")
            return handle_start_debugging_response(m.get<StartDebuggingResponse>());
        if (command == "stepBack")
            return handle_step_back_response(m.get<StepBackResponse>());
        if (command == "stepIn")
            return handle_step_in_response(m.get<StepInResponse>());
        if (command == "stepInTargets")
            return handle_step_in_targets_response(m.get<StepInTargetsResponse>());
        if (command == "stepOut")
            return handle_step_out_response(m.get<StepOutResponse>());
        if (command == "terminate")
            return handle_terminate_response(m.get<TerminateResponse>());
        if (command == "terminateThreads")
            return handle_terminate_threads_response(m.get<TerminateThreadsResponse>());
        if (command == "threads")
            return handle_threads_response(m.get<ThreadsResponse>());
        if (command == "variables")
            return handle_variables_response(m.get<VariablesResponse>());
        if (command == "writeMemory")
            return handle_write_memory_response(m.get<WriteMemoryResponse>());
    }
};

} // namespace dap_dbgeng::protocol
